version: '3.8'

services:
  backend:
    container_name: backend
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/backend/
    ports:
      - 8000:8000
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "5173:5173"
    volumes: 
      - ./frontend:/frontend
    command: npm run dev
    depends_on:
      - backend