# Generated by Django 5.0.6 on 2024-07-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Название')),
                ('bik', models.CharField(blank=True, max_length=50, null=True, verbose_name='БИК')),
                ('cor_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кор.счёт')),
                ('addr', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Банк',
                'verbose_name_plural': 'Банки',
                'db_table': 's_banks',
            },
        ),
        migrations.CreateModel(
            name='Gas_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип системы газоснабжения',
                'verbose_name_plural': 'Типы системы газоснабжения',
                'db_table': 's_gas_type',
            },
        ),
        migrations.CreateModel(
            name='Priority_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип приоритетность дома',
                'verbose_name_plural': 'Типы приоритетность дома',
                'db_table': 's_priority_type',
            },
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'db_table': 's_region',
            },
        ),
        migrations.CreateModel(
            name='Regions_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип региона',
                'verbose_name_plural': 'Типы регионов',
                'db_table': 's_region_type',
            },
        ),
        migrations.CreateModel(
            name='Roof_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Материал крышии')),
            ],
            options={
                'verbose_name': 'Материал крыши',
                'verbose_name_plural': 'Материалы крыш',
                'db_table': 's_roof_material',
            },
        ),
        migrations.CreateModel(
            name='Rule_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип управления',
                'verbose_name_plural': 'Типы управления',
                'db_table': 's_rule_type',
            },
        ),
        migrations.CreateModel(
            name='Streets_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Тип улицы',
                'verbose_name_plural': 'Типы улиц',
                'db_table': 's_street_type',
            },
        ),
        migrations.CreateModel(
            name='Wall_Materials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Материал стен')),
            ],
            options={
                'verbose_name': 'Материал стен',
                'verbose_name_plural': 'Материалы стен',
                'db_table': 's_wall_material',
            },
        ),
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Город')),
                ('ymap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты')),
                ('region', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogs.regions', verbose_name='Региион')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'db_table': 's_city',
            },
        ),
        migrations.AddField(
            model_name='regions',
            name='type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogs.regions_types', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Streets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Улица')),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogs.cities', verbose_name='Город')),
                ('type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='catalogs.streets_types', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
                'db_table': 's_street',
            },
        ),
    ]
