# Generated by Django 5.0.6 on 2024-07-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Builds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер')),
                ('litera', models.CharField(blank=True, max_length=30, null=True, verbose_name='Литера')),
                ('corpse', models.CharField(blank=True, max_length=30, null=True, verbose_name='Корпус')),
                ('ymap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Координаты')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='builds_images', verbose_name='Изображение')),
                ('year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Год постройки')),
                ('floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этажей')),
                ('q_porchs', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Подъездов')),
                ('q_lifts', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Лифтов')),
                ('q_flats', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Квартир')),
                ('q_uu', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Узлов учёта тепловой энергии')),
                ('s_live', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Площадь жилых помещений')),
                ('s_no_live', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Площадь нежилых помещений')),
                ('s_mop', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Площадь МОП')),
                ('s_zem', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=7, null=True, verbose_name='Площадь земельного участка')),
                ('kadnum_zem', models.CharField(blank=True, max_length=50, null=True, verbose_name='Кадастровый номер')),
                ('has_garret', models.BooleanField(blank=True, default=False, null=True, verbose_name='Наличие чердака')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogs.cities', verbose_name='Город')),
                ('gas_type', models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.gas_types', verbose_name='Тип системы газоснабжения')),
                ('priority', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.priority_types', verbose_name='Приоритетность')),
                ('roof_material', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.roof_materials', verbose_name='Материал крыши')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='catalogs.streets', verbose_name='Улица')),
                ('wall_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.wall_materials', verbose_name='Материал стен')),
            ],
            options={
                'verbose_name': 'Дом',
                'verbose_name_plural': 'Дома',
                'db_table': 'd_build',
            },
        ),
        migrations.CreateModel(
            name='BuildManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='01.01.2009', null=True, verbose_name='Дата начала упарвления')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.companies', verbose_name='Организация')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.builds', verbose_name='Организация')),
            ],
            options={
                'verbose_name': 'Управляющая компания',
                'verbose_name_plural': 'Управляющие компании',
                'db_table': 'z_build_management',
            },
        ),
        migrations.CreateModel(
            name='BuildSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_str', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Город')),
                ('addr_str', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Улица')),
                ('management_company_name', models.CharField(blank=True, max_length=3000, null=True, verbose_name='Управляющая компания')),
                ('report_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Отчётов')),
                ('uu_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество узлов учёта')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.builds', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Сводная таблица по домам',
                'verbose_name_plural': 'Сводная таблица по домам',
                'db_table': 'z_build_summary',
            },
        ),
    ]
