# Generated by Django 5.0.6 on 2024-07-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('year_before', models.BigIntegerField(verbose_name='Год до')),
                ('photo_before', models.ImageField(blank=True, null=True, upload_to='achieves_images', verbose_name='Изображение до')),
                ('info_before', models.CharField(blank=True, max_length=2000, verbose_name='Описание до')),
                ('year_after', models.BigIntegerField(verbose_name='Год после')),
                ('photo_after', models.ImageField(blank=True, null=True, upload_to='achieves_images', verbose_name='Изображение после')),
                ('info_after', models.CharField(blank=True, max_length=2000, verbose_name='Описание после')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.builds', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'db_table': 's_achievements',
            },
        ),
    ]
