# Generated by Django 5.0.6 on 2024-07-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='year_after',
            field=models.BigIntegerField(blank=True, verbose_name='Год после'),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='year_before',
            field=models.BigIntegerField(blank=True, verbose_name='Год до'),
        ),
    ]
