# Generated by Django 5.0.6 on 2024-07-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000, verbose_name='Полное наименование')),
                ('short_name', models.CharField(max_length=255, verbose_name='Краткое наименование')),
                ('ogrn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ОГРН')),
                ('inn', models.CharField(blank=True, max_length=50, null=True, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=50, null=True, verbose_name='КПП')),
                ('web_site', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('account', models.CharField(blank=True, max_length=50, null=True, verbose_name='Счёт')),
                ('addr_jur', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес юридический')),
                ('addr_post', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Адрес почтовый')),
                ('bank', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogs.banks', verbose_name='Банк')),
                ('city', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalogs.cities', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Оргнанизация',
                'verbose_name_plural': 'Оргнанизации',
                'db_table': 'd_companies',
            },
        ),
    ]
