# Generated by Django 5.0.6 on 2024-07-02 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citizens_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Состояние гражданина',
                'verbose_name_plural': 'Состояния гражданина',
                'db_table': 's_citizen_status',
            },
        ),
        migrations.CreateModel(
            name='Citizens_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип гражданина',
                'verbose_name_plural': 'Типы граждан',
                'db_table': 's_citizen_type',
            },
        ),
        migrations.CreateModel(
            name='Citizens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=150, verbose_name='Отчество')),
                ('family_name_r', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия в родительном падеже')),
                ('first_name_r', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя в родительном падеже')),
                ('second_name_r', models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество в родительном падеже')),
                ('city_str', models.CharField(blank=True, max_length=50, null=True, verbose_name='Город')),
                ('street_str', models.CharField(blank=True, max_length=50, null=True, verbose_name='Улица')),
                ('build_str', models.CharField(blank=True, max_length=30, null=True, verbose_name='Дом')),
                ('flat', models.CharField(blank=True, max_length=10, null=True, verbose_name='Квартира')),
                ('comment', models.TextField(blank=True, max_length=4000, null=True, verbose_name='Комментарий')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=70, verbose_name='Имейл')),
                ('date_create', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создения')),
                ('office_notification_date', models.DateField(blank=True, null=True, verbose_name='Дата отправки уведомления в офис')),
                ('uk_notification_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки уведомления в управляющую компанию')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код из смс')),
                ('code_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата отправки кода СМС')),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='builds.builds', verbose_name='Дом')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='citizens.citizens_status', verbose_name='Статус')),
                ('type', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='citizens.citizens_type', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Граждани',
                'verbose_name_plural': 'Граждане',
                'db_table': 'd_citizen',
            },
        ),
    ]
